name: 'Configure AWS Credentials'
description: 'Sets up AWS credentials for GitHub Actions'

inputs:
  aws-access-key-id:
    required: true
    description: 'AWS Access Key ID'
  aws-secret-access-key:
    required: true
    description: 'AWS Secret Access Key'
  aws-region:
    required: true
    description: 'AWS Region'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      shell: bash
      run: |
        aws configure set aws_access_key_id ${{ inputs.aws-access-key-id }}
        aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key }}
        aws configure set region ${{ inputs.aws-region }}
