services:
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./logs/api-server:/logs
    environment:
      - NODE_ENV=production
      - PORT=4000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
