services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    volumes:
      - ./logs/web:/logs
      # Comment out this volume mount that's overriding the build
      # - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3050
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:3050/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    network_mode: host

volumes:
  logs:
