version: '3.8'

services:
  api:
    image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/lumixlabs/swift-api:latest
    ports:
      - "3000:3000" 
    restart: always
    volumes:
      - /app/logs/api:/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - swift-network
  web:
    image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/lumixlabs/swift-web:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - /app/logs/web:/logs
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - swift-network

networks:
  swift-network:
    driver: bridge
