name: "Create Docker Compose File"
description: "Creates a docker-compose.yml file based on modules to deploy"

inputs:
  registry:
    description: "ECR registry URL"
    required: true
  modules_to_deploy:
    description: "Comma-separated list of modules to deploy"
    required: true
  container_image_api:
    description: "Full image URI for API container"
    required: false
  container_image_web:
    description: "Full image URI for web container"
    required: false

runs:
  using: "composite"
  steps:
    - name: Create docker-compose file
      shell: bash
      run: |
        mkdir -p deploy

        # Copy from template
        cp ${{ github.action_path }}/../templates/docker-compose.yml deploy/docker-compose.yml

        echo "Registry URL: ${{ inputs.registry }}"
        echo "Modules to deploy: ${{ inputs.modules_to_deploy }}"
        
        # Debug image values to check for type confusion
        API_IMAGE="${{ inputs.container_image_api }}"
        WEB_IMAGE="${{ inputs.container_image_web }}"
        
        echo "API image value: '$API_IMAGE'"
        echo "Web image value: '$WEB_IMAGE'"
        
        # Check for boolean-like values which might indicate type confusion
        if [[ "$API_IMAGE" == "true" || "$API_IMAGE" == "false" ]]; then
          echo "Warning: API image value appears to be a boolean - this may indicate type confusion in the workflow"
        fi
        
        if [[ "$WEB_IMAGE" == "true" || "$WEB_IMAGE" == "false" ]]; then
          echo "Warning: Web image value appears to be a boolean - this may indicate type confusion in the workflow"
        fi

        # Replace dockerfile placeholders with image values
        sed -i "s|image: CONTAINER_IMAGE_WEB|image: ${{ inputs.container_image_web }}|g" deploy/docker-compose.yml
        sed -i "s|image: CONTAINER_IMAGE_API|image: ${{ inputs.container_image_api }}|g" deploy/docker-compose.yml

        # Map module names to service names in docker-compose.yml
        declare -A MODULE_MAP
        MODULE_MAP["api"]="api-server"
        MODULE_MAP["web"]="web"

        # Always deploy all modules (simplified approach per requirements)
        echo "Creating docker-compose.yml for all modules"
        
        # Display final docker-compose file for debugging
        echo "==== Final docker-compose.yml content ===="
        cat deploy/docker-compose.yml
        echo "==========================================="