name: 'Create Docker Compose File'
description: 'Creates a docker-compose.yml file based on modules to deploy'

inputs:
  registry:
    description: 'ECR registry URL'
    required: true
  modules_to_deploy:
    description: 'Comma-separated list of modules to deploy'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create docker-compose file
      shell: bash
      run: |
        mkdir -p deploy
        cp ${{ github.action_path }}/../templates/docker-compose.yml deploy/docker-compose.yml
        
        # Replace variables in the template
        sed -i "s|\${AWS_ECR_REGISTRY}|${{ inputs.registry }}|g" deploy/docker-compose.yml
        
        # If specific modules were specified, remove other modules
        if [ -n "${{ inputs.modules_to_deploy }}" ]; then
          IFS=',' read -ra MODULES <<< "${{ inputs.modules_to_deploy }}"
          ALL_MODULES=("api" "web" "mcp-server")
          
          # Find modules to remove
          for MODULE in "${ALL_MODULES[@]}"; do
            if [[ ! " ${MODULES[*]} " =~ " ${MODULE} " ]]; then
              # Remove the module section from docker-compose.yml
              sed -i "/^  ${MODULE}:/,/^  [a-z]\\|^$/d" deploy/docker-compose.yml
            fi
          done
        fi
