name: 'Create Deployment Script'
description: 'Generates the deployment shell script for EC2'

runs:
  using: "composite"
  steps:
    - name: Create deployment script
      shell: bash
      run: |
        mkdir -p deploy
        
        # Copy the deployment script template to the output file
        cp "${GITHUB_WORKSPACE}/.github/workflows/deploy/templates/deployment-script-template.sh" deploy/run-deployment.sh
        
        # Make the script executable
        chmod +x deploy/run-deployment.sh