name: 'Login to Amazon ECR'
description: 'Authenticates with Amazon ECR'

inputs:
  aws-region:
    required: true
    description: 'AWS Region'
  aws-account-id:
    required: true
    description: 'AWS Account ID'

outputs:
  registry:
    description: 'The ECR registry URL'
    value: ${{ steps.login.outputs.registry }}

runs:
  using: 'composite'
  steps:
    - name: Login to Amazon ECR
      id: login
      shell: bash
      run: |
        aws ecr get-login-password --region ${{ inputs.aws-region }} | docker login --username AWS --password-stdin ${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
        echo "registry=${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com" >> $GITHUB_OUTPUT
