name: 'Verify Deployment'
description: 'Verifies the deployment of modules on EC2 instance'

inputs:
  instance_id:
    description: 'EC2 instance ID'
    required: false
  instance_ip:
    description: 'EC2 instance IP'
    required: true
  modules_to_deploy:
    description: 'Comma-separated list of modules to deploy'
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify Deployment
      shell: bash
      run: |
        INSTANCE_ID="${{ inputs.instance_id }}"
        INSTANCE_IP="${{ inputs.instance_ip }}"
        
        # Check if we're using fallback values from Terraform - fail immediately
        if [[ "$INSTANCE_IP" == "fallback_ip_for_pipeline_continuity" ]] || [[ "$INSTANCE_ID" == "fallback_id_for_pipeline_continuity" ]]; then
          echo "ERROR: Received fallback values for infrastructure parameters."
          echo "This indicates that Terraform did not properly output instance information."
          echo "Verification cannot proceed."
          
          # Exit with error to stop the workflow
          exit 1
        fi
        
        if [ -z "$INSTANCE_ID" ] || [ "$INSTANCE_ID" == "null" ]; then
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=public-ip-address,Values=$INSTANCE_IP" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)
            
          if [ "$INSTANCE_ID" == "None" ] || [ -z "$INSTANCE_ID" ]; then
            echo "Error: Could not determine instance ID for IP $INSTANCE_IP"
            exit 1
          fi
        fi
        
        echo "Verifying deployment of modules: ${{ inputs.modules_to_deploy }}"
        
        # Give services time to start
        echo "Waiting for services to start..."
        sleep 30
        
        # Check docker-compose status first
        echo "Checking docker-compose status..."
        DOCKER_COMPOSE_STATUS_CMD_ID=$(aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters commands="[\"cd /app && docker-compose ps\"]" \
          --output text \
          --query "Command.CommandId" || echo "Command failed for docker-compose status")
          
        if [[ "$DOCKER_COMPOSE_STATUS_CMD_ID" != *"Command failed"* ]]; then
          sleep 5
          
          # Get verification result
          aws ssm get-command-invocation \
            --command-id "$DOCKER_COMPOSE_STATUS_CMD_ID" \
            --instance-id "$INSTANCE_ID" \
            --query "StandardOutputContent" \
            --output text || echo "Could not verify docker-compose status"
        else
          echo "Failed to check docker-compose status. Verification will continue but may not be accurate."
        fi
        
        # Verify individual services using SSM
        IFS=',' read -ra MODULES <<< "${{ inputs.modules_to_deploy }}"
        VERIFICATION_SUCCESS=true
        
        for MODULE in "${MODULES[@]}"; do
          if [[ "$MODULE" == "api" ]]; then
            echo "Checking API service..."
            
            VERIFY_CMD_ID=$(aws ssm send-command \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --parameters commands="[\"cd /app && docker-compose ps api && curl -s http://localhost:4000/health || echo 'API service is not responding'\"]" \
              --output text \
              --query "Command.CommandId" || echo "Command failed for API service")
              
            # Only continue if command succeeded
            if [[ "$VERIFY_CMD_ID" != *"Command failed"* ]]; then
              sleep 5
              
              # Get verification result
              API_STATUS=$(aws ssm get-command-invocation \
                --command-id "$VERIFY_CMD_ID" \
                --instance-id "$INSTANCE_ID" \
                --query "StandardOutputContent" \
                --output text || echo "Could not verify API service")
                
              echo "$API_STATUS"
              
              if [[ "$API_STATUS" == *"not responding"* ]]; then
                echo "ERROR: API service verification failed"
                VERIFICATION_SUCCESS=false
              fi
            else
              echo "ERROR: Failed to execute API verification command"
              VERIFICATION_SUCCESS=false
            fi
            
          elif [[ "$MODULE" == "web" ]]; then
            echo "Checking Web service..."
            
            VERIFY_CMD_ID=$(aws ssm send-command \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --parameters commands="[\"cd /app && docker-compose ps web && curl -s http://localhost:80/ | head -20 || echo 'Web service is not responding'\"]" \
              --output text \
              --query "Command.CommandId" || echo "Command failed for Web service")
              
            # Only continue if command succeeded
            if [[ "$VERIFY_CMD_ID" != *"Command failed"* ]]; then
              sleep 5
              
              # Get verification result
              WEB_STATUS=$(aws ssm get-command-invocation \
                --command-id "$VERIFY_CMD_ID" \
                --instance-id "$INSTANCE_ID" \
                --query "StandardOutputContent" \
                --output text || echo "Could not verify Web service")
                
              echo "$WEB_STATUS"
              
              if [[ "$WEB_STATUS" == *"not responding"* ]]; then
                echo "ERROR: Web service verification failed"
                VERIFICATION_SUCCESS=false
              fi
            else
              echo "ERROR: Failed to execute Web verification command"
              VERIFICATION_SUCCESS=false
            fi
          fi
        done

        # Final verification message and status
        if [ "$VERIFICATION_SUCCESS" = true ]; then
          echo "Deployment verification completed successfully for modules: ${{ inputs.modules_to_deploy }}"
        else
          echo "ERROR: Deployment verification failed for one or more modules"
          exit 1
        fi
