version: '3.8'

services:
  # API service template
  api:
    image: ${REGISTRY}/lumixlabs/swift-api:latest
    ports:
      - "3000:3000" 
    restart: always
    volumes:
      - /app/logs/api:/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - swift-network

  # Web service template
  web:
    image: ${REGISTRY}/lumixlabs/swift-web:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - /app/logs/web:/logs
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - swift-network

  # MCP server service template
  mcp-server:
    image: ${REGISTRY}/lumixlabs/swift-mcp-server:latest
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - /app/logs/mcp-server:/logs
    environment:
      - NODE_ENV=production
      - PORT=3001
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - swift-network

networks:
  swift-network:
    driver: bridge