name: Build and Push Docker Images

on:
  push:
    branches: [master, main]
    paths:
      - "api/**"
      - "web/**"
      - "mcp-server/**"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      forceBuildApi:
        description: "Force build of API image"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      forceBuildWeb:
        description: "Force build of Web image"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      forceBuildMcpServer:
        description: "Force build of MCP Server image"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  # This workflow now simply calls the CI/CD orchestration pipeline
  trigger-cicd:
    name: Trigger CI/CD Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Trigger CI/CD Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-cicd
          client-payload: |
            {
              "forceInfraUpdate": "false",
              "skipDeployment": "false"
            }
