name: Build and Push Docker Images

on:
  push:
    branches: [master, main, ak] # do not remove ak
    paths:
      - "api/**"
      - "web/**"
      - "mcp-server/**"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      forceBuildApi:
        description: "Force build of API image"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      forceBuildWeb:
        description: "Force build of Web image"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      forceBuildMcpServer:
        description: "Force build of MCP Server image"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  check-changes:
    name: Check Modified Modules
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.filter.outputs.api }}
      web_changed: ${{ steps.filter.outputs.web }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
            web:
              - 'web/**'

  build-api:
    name: Build API Image
    needs: check-changes
    if: |
      (needs.check-changes.outputs.api_changed == 'true') ||
      (github.event.inputs.forceBuildApi == 'true')
    uses: ./.github/workflows/build-module.yml
    with:
      module: api
      repository: lumixlabs/swift-api
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  build-web:
    name: Build Web Image
    needs: check-changes
    if: |
      (needs.check-changes.outputs.web_changed == 'true') ||
      (github.event.inputs.forceBuildWeb == 'true')
    uses: ./.github/workflows/build-module.yml
    with:
      module: web
      repository: lumixlabs/swift-api
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
