name: CI/CD Pipeline

on:
  push:
    branches: [master, main, ak]
    paths:
      - \"api/**\"
      - \"web/**\"
      - \"mcp-server/**\"
      - \"terraform/**\"
      - \".github/workflows/**\"
  workflow_dispatch:
    inputs:
      forceInfraUpdate:
        description: \"Force infrastructure update\"
        required: false
        default: \"false\"
        type: choice
        options:
          - \"true\"
          - \"false\"
      skipDeployment:
        description: \"Skip deployment step\"
        required: false
        default: \"false\"
        type: choice
        options:
          - \"true\"
          - \"false\"

jobs:
  infrastructure:
    name: Infrastructure Deployment
    uses: ./.github/workflows/infrastructure.yml
    with:
      forceInfraUpdate: ${{ github.event.inputs.forceInfraUpdate || 'false' }}
    secrets: inherit

  deploy:
    name: Application Deployment
    needs: infrastructure
    if: ${{ always() && (needs.infrastructure.result == 'success') && (github.event.inputs.skipDeployment != 'true') }}
    uses: ./.github/workflows/deploy.yml
    with:
      deploymentParams: ${{ needs.infrastructure.outputs.deployment_params }}
    secrets: inherit
    continue-on-error: false
