name: Deploy Application

on:
  workflow_call:
    inputs:
      infrastructureParams:
        required: true
        type: string
        description: "JSON string containing infrastructure parameters"
      modulesToDeploy:
        required: true
        type: string
        description: "Comma-separated list of modules to deploy"
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      EC2_SSH_KEY:
        required: false
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      CONTAINER_IMAGE_API:
        required: false
      CONTAINER_IMAGE_WEB:
        required: false
    outputs:
      deployment_status:
        description: "Status of the deployment"
        value: ${{ jobs.deploy.outputs.status }}
      deployment_debug_info:
        description: "Debug information from deployment"
        value: ${{ jobs.deploy.outputs.debug_info }}

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      status: ${{ steps.deployment-result.outputs.status }}
      debug_info: ${{ steps.deployment-result.outputs.debug_info }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      # === Parse Parameters ===
      - name: Parse parameters
        id: parse-params
        uses: ./.github/workflows/deploy/parse-params
        with:
          infrastructureParams: ${{ inputs.infrastructureParams }}
          modulesToDeploy: ${{ inputs.modulesToDeploy }}

      # Explicitly type check parameters for better debugging
      - name: Validate parameter types
        id: validate-params
        run: |
          echo "Validating parameter types for debugging..."
          
          # Check instance_id
          INSTANCE_ID="${{ steps.parse-params.outputs.instance_id }}"
          echo "Instance ID: '$INSTANCE_ID' (Type: $(if [[ "$INSTANCE_ID" =~ ^[0-9]+$ ]]; then echo 'numeric'; elif [[ -z "$INSTANCE_ID" ]]; then echo 'empty string'; else echo 'string'; fi))"
          
          # Check modules_to_deploy
          MODULES="${{ steps.parse-params.outputs.modules_to_deploy }}"
          echo "Modules to deploy: '$MODULES' (Type: $(if [[ -z "$MODULES" ]]; then echo 'empty string'; else echo 'string'; fi))"
          
          # Validate comma-separated format
          if [[ "$MODULES" == *","* ]]; then
            echo "✓ Modules list contains commas as expected"
          else
            echo "⚠ Modules list doesn't contain commas - might be a single module or empty"
          fi
          
          # Check if modules are in expected list
          IFS=',' read -ra MODULE_ARRAY <<< "$MODULES"
          for MODULE in "${MODULE_ARRAY[@]}"; do
            if [[ "$MODULE" == "api" || "$MODULE" == "web" ]]; then
              echo "✓ Valid module: $MODULE"
            else
              echo "⚠ Unknown module: '$MODULE'"
            fi
          done

      # === Create Deployment Files ===
      - name: Create docker-compose file
        uses: ./.github/workflows/deploy/create-docker-compose
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          modules_to_deploy: ${{ steps.parse-params.outputs.modules_to_deploy }}
          container_image_api: ${{ secrets.CONTAINER_IMAGE_API }}
          container_image_web: ${{ secrets.CONTAINER_IMAGE_WEB }}

      - name: Create deployment script
        uses: ./.github/workflows/deploy/create-deployment-script

      - name: Encode files for secure transfer
        id: encode-files
        run: |
          DOCKER_COMPOSE_BASE64=$(base64 -w 0 deploy/docker-compose.yml)
          DEPLOYMENT_SCRIPT_BASE64=$(base64 -w 0 deploy/run-deployment.sh)

          echo "docker_compose_base64=${DOCKER_COMPOSE_BASE64}" >> $GITHUB_OUTPUT
          echo "deployment_script_base64=${DEPLOYMENT_SCRIPT_BASE64}" >> $GITHUB_OUTPUT

      # === Deploy to Instance ===
      - name: Deploy using SSM
        id: deploy-to-instance
        uses: ./.github/workflows/deploy/deploy-via-ssm
        with:
          instance_id: ${{ steps.parse-params.outputs.instance_id }}
          instance_ip: ${{ steps.parse-params.outputs.instance_ip }}
          docker_compose_base64: ${{ steps.encode-files.outputs.docker_compose_base64 }}
          deployment_script_base64: ${{ steps.encode-files.outputs.deployment_script_base64 }}
          registry: ${{ steps.login-ecr.outputs.registry }}
          aws_region: ${{ secrets.AWS_REGION }}
          container_image_api: ${{ secrets.CONTAINER_IMAGE_API }}
          container_image_web: ${{ secrets.CONTAINER_IMAGE_WEB }}

      - name: Set deployment result
        id: deployment-result
        run: |
          # Capture debug information
          if [ "${{ steps.deploy-to-instance.outcome }}" == "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "Deployment completed successfully"
            
            # Create JSON without heredoc syntax
            echo 'debug_info={"status":"success","instance_id":"${{ steps.parse-params.outputs.instance_id }}","instance_ip":"${{ steps.parse-params.outputs.instance_ip }}","modules_deployed":"${{ steps.parse-params.outputs.modules_to_deploy }}","timestamp":"'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"}'  >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "Deployment failed"
            
            # Create JSON without heredoc syntax
            echo 'debug_info={"status":"failure","instance_id":"${{ steps.parse-params.outputs.instance_id }}","instance_ip":"${{ steps.parse-params.outputs.instance_ip }}","modules_deployed":"${{ steps.parse-params.outputs.modules_to_deploy }}","error_phase":"ssm_deployment","timestamp":"'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'","failure_details":"Check GitHub Actions logs for detailed error message"}' >> $GITHUB_OUTPUT
          fi
