name: Deploy Application

on:
  workflow_call:
    inputs:
      infrastructureParams:
        required: true
        type: string
        description: 'JSON string containing infrastructure parameters'
      modulesToDeploy:
        required: true
        type: string
        description: 'Comma-separated list of modules to deploy'
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      EC2_SSH_KEY:
        required: false
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch:
    inputs:
      instance_ip:
        description: 'EC2 Instance IP'
        required: true
        type: string
      modules_to_deploy:
        description: 'Comma-separated list of modules to deploy (api,web)'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy Application
    uses: ./.github/workflows/deploy/main.yml
    with:
      infrastructureParams: ${{ inputs.infrastructureParams }}
      modulesToDeploy: ${{ inputs.modulesToDeploy }}
      instance_ip: ${{ inputs.instance_ip }}
      modules_to_deploy: ${{ inputs.modules_to_deploy }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}