name: Terraform Workflow

on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string
        description: "Terraform action to perform (plan or apply)"
    outputs:
      infrastructure_params:
        description: "Infrastructure parameters as JSON"
        value: ${{ jobs.terraform.outputs.infrastructure_params }}
    secrets:
      TERRAFORM_API_TOKEN:
        required: true
      SSH_PRIVATE_KEY:
        required: false

jobs:
  terraform:
    name: Terraform ${{ inputs.action }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./terraform
    outputs:
      infrastructure_params: ${{ steps.extract-params.outputs.infrastructure_params }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
          terraform_wrapper: false

      - name: Debug variables.tf
        run: cat variables.tf

      - name: Debug backend.tf
        run: cat backend.tf

      # Initialize with -upgrade flag to ignore the lock file
      - name: Terraform Init
        id: init
        env:
          TF_AUTH: ${{ secrets.TERRAFORM_API_TOKEN }}
          TF_LOG: DEBUG
        run: terraform init -input=false -upgrade

      - name: Setup SSH key
        run: |
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "TF_VAR_ssh_private_key_content<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Debug after init failure
        if: failure()
        run: |
          echo "=== Terraform state debug ==="
          ls -la
          find . -name "*.tfstate*" -type f -exec ls -la {} \;
          find . -name "*.tflock*" -type f -exec ls -la {} \;
          echo "=== Terraform providers debug ==="
          terraform providers || echo "Cannot run providers command"
          echo "=== Terraform validate debug ==="
          terraform validate || echo "Cannot validate"

      - name: Terraform Plan
        if: inputs.action == 'plan'
        id: plan
        env:
          TF_AUTH: ${{ secrets.TERRAFORM_API_TOKEN }}
        run: terraform plan

      - name: Terraform Apply
        if: inputs.action == 'apply'
        env:
          TF_AUTH: ${{ secrets.TERRAFORM_API_TOKEN }}
        run: terraform apply -auto-approve

      - name: Extract Infrastructure Parameters
        if: inputs.action == 'apply'
        id: extract-params
        run: |
          # Extract values individually using -raw to avoid JSON formatting issues
          INSTANCE_IP=$(terraform output -raw instance_public_ip 2>/dev/null || echo "")
          INSTANCE_ID=$(terraform output -raw instance_id 2>/dev/null || echo "")

          # Create compact single-line JSON without newlines or special characters
          INFRASTRUCTURE_PARAMS="{\"instance_ip\":\"$INSTANCE_IP\",\"instance_id\":\"$INSTANCE_ID\"}"

          echo "infrastructure_params=$INFRASTRUCTURE_PARAMS" >> $GITHUB_OUTPUT
