# Cloudflare Pages Configuration

[build]
  command = "npm install --no-engine-strict && npm run build"
  output_directory = "/out"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20.12.1"
  NPM_VERSION = "10.5.0"
  NEXT_TELEMETRY_DISABLED = "1"
